### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MichaelLookinForSumHcks** [Devik55/Hackemos#2]
It syas i must be on conjuguemos site and open a lesson when i am.

**Comment by Devik55** [comment]
mind sendig me the link of the lesson when you are on it? you might be using a unsupported lesson type i havent heard of

**Comment by Devik55** [comment]
the new 2.1 update probabally fixed this. try it again

**Comment by MichaelLookinForSumHcks** [comment]
https://conjuguemos.com/verb/homework/1980093#dashboard
https://conjuguemos.com/vocabulary/homework/2518510

**Comment by MichaelLookinForSumHcks** [comment]
> the new 2.1 update probabally fixed this. try it again

mk

**Comment by MichaelLookinForSumHcks** [comment]
it worked. ty

**Comment by MichaelLookinForSumHcks** [comment]
nvm it says it will be updated and the screen comes up with all the data after i use finish lesson, but it jst loads forever

**Comment by MichaelLookinForSumHcks** [comment]
the change data one doesnt work either

**Comment by MichaelLookinForSumHcks** [comment]
oh btw can u also make ixl hacks?

**Comment by MichaelLookinForSumHcks** [comment]
it says, The lesson will be skipped with 97% accuracy and the time taken will be 5:00. The lesson start date will show as 12/8/2024, 11:29:49 AM and the end date will show as 12/8/2024, 11:34:49 AM. Confirm lesson skip? Once it reloads you might have to leave the lesson and reenter to fully submit.

**Comment by Devik55** [comment]
the reason why it infinetly loads is that on the vocabulary assignments it uses the change data method and does activity.save, then refreshes but on some computers it doesnt load and if it does the lesson restarts but the reason i added the part that says you might have to reenter the lesson is because thats what you need to do to fully submit

**Comment by Devik55** [comment]
change data only works on custom activities. the skipper works on guided practice too though

**Comment by Devik55** [comment]
sorry for the inconviences. i know how to fix them now and it will be updated shortly.

**Comment by Devik55** [comment]
the new version fixed these im 90% sure. try again

**Comment by MichaelLookinForSumHcks** [comment]
> the new version fixed these im 90% sure. try again

k imma try it rn

**Comment by MichaelLookinForSumHcks** [comment]
wydm by reenter it doesnt stop loading

**Comment by MichaelLookinForSumHcks** [comment]
u still there?

**Comment by Devik55** [comment]
i dont know why it takes awhile to load for you but theres no shot its infininte

**Comment by Devik55** [comment]
just wait for a bit

**Comment by Devik55** [comment]
havent had this issue before

**Comment by MichaelLookinForSumHcks** [comment]
k

**Comment by MichaelLookinForSumHcks** [comment]
its still loading

**Comment by Devik55** [comment]
bru

**Comment by Devik55** [comment]
ok just try a different lesson type

**Comment by MichaelLookinForSumHcks** [comment]
kk

**Comment by MichaelLookinForSumHcks** [comment]
i tried a dif lesson but its still loading

**Comment by MichaelLookinForSumHcks** [comment]
idk wt the guided practice is

**Comment by MichaelLookinForSumHcks** [comment]
graded practice?

**Comment by Devik55** [comment]
nvm

**Comment by Devik55** [comment]
i just made another update lol

**Comment by MichaelLookinForSumHcks** [comment]
k ill try it

**Comment by Devik55** [comment]
2.2.1 changed the skipper method

**Comment by Devik55** [comment]
my teacher doesnt assign these types of lessons so its hard to test and make stuff for them

**Comment by Devik55** [comment]
everyone has different stuff so

**Comment by MichaelLookinForSumHcks** [comment]
yea

**Comment by MichaelLookinForSumHcks** [comment]
did u check the links i sent?

**Comment by MichaelLookinForSumHcks** [comment]
after sum time of loading the works turn into --

**Comment by MichaelLookinForSumHcks** [comment]
k imma leave and let them load see if it works

**Comment by Devik55** [comment]
> did u check the links i sent?

yes but i deleted them because it might have sensitive info because they were custom made by your teacher
i didnt want them to be public because they could maybe find your school?

**Comment by MichaelLookinForSumHcks** [comment]
ohhhh

**Comment by MichaelLookinForSumHcks** [comment]
i can email them to u privatly?

**Comment by Devik55** [comment]
i already saw it its fine

**Comment by MichaelLookinForSumHcks** [comment]
k

**Comment by MichaelLookinForSumHcks** [comment]
the skipper has always been working for me

**Comment by Devik55** [comment]
if the issues continue would you want to share your screen on discord or something

**Comment by Devik55** [comment]
oh ok

**Comment by Devik55** [comment]
thanks for your patience you made the hack a lot better by reporting the bugs

**Comment by MichaelLookinForSumHcks** [comment]
ty

**Comment by MichaelLookinForSumHcks** [comment]
Sure maybe later

**Comment by MichaelLookinForSumHcks** [comment]
i gtg ill try later

**Comment by MichaelLookinForSumHcks** [comment]
this time imma wait for the timer to run out before clicking save

**Comment by MichaelLookinForSumHcks** [comment]
it said: We cannot submit your answer now. Please try again later...

**Comment by Devik55** [comment]
> this time imma wait for the timer to run out before clicking save

what are you talking about

**Comment by MichaelLookinForSumHcks** [comment]
like theres a timer for the graded practice. imma wait for it to run out

**Comment by MichaelLookinForSumHcks** [comment]
it didnt work

**Comment by Devik55** [comment]
can you call me on discord and screenshare

**Comment by Devik55** [comment]
username is "devik_dev"

**Comment by Devik55** [comment]
> this time imma wait for the timer to run out before clicking save

you dont need to do that the hack spoofs the timer stuff

**Comment by MichaelLookinForSumHcks** [comment]
i found a way to make it work

**Comment by MichaelLookinForSumHcks** [comment]
could u also make the changes to the bookmarklet?

**Comment by Devik55** [comment]
what did you change

**Comment by Devik55** [comment]
also the bookmarkllet auto updates because it fetches from the script

**Comment by MichaelLookinForSumHcks** [comment]
i just left the submit screen there and went to play sum basketball. and when i came back i clicked submit and it worked. Cuz the timer ran out

**Comment by MichaelLookinForSumHcks** [comment]
im trying to do it again but its not working. i prob have to wait longer.

**Comment by MichaelLookinForSumHcks** [comment]
it says.
We cannot submit you answer now. Please try again later...

**Comment by MichaelLookinForSumHcks** [comment]
so far its only worked once

**Comment by MichaelLookinForSumHcks** [comment]
> can you call me on discord and screenshare
uhhm maybe later

**Comment by MichaelLookinForSumHcks** [comment]
are there any changes u could make to stop the infinite loading cuz the method im trying isnt working.

**Comment by Devik55** [comment]
ill try but ik its unrelated but its crazy i just so happen to open github 1 min after you post something not even knowing or getting a notification

**Comment by MichaelLookinForSumHcks** [comment]
alr

**Comment by Devik55** [comment]
it works on other lessons though which im assuming you dont have but those are the ones i use

**Comment by MichaelLookinForSumHcks** [comment]
oof

**Comment by MichaelLookinForSumHcks** [comment]
uhhm idk honestly ill talk tmmwr

**Comment by MichaelLookinForSumHcks** [comment]
> it works on other lessons though which im assuming you dont have but those are the ones i use

can u send me a link for those lessons i wanna see if its just my comp

**Comment by MichaelLookinForSumHcks** [comment]
cuz its only worked once for me

**Comment by MichaelLookinForSumHcks** [comment]
u can ask chat gpt?

**Comment by Devik55** [comment]
bruh i figured it all out

**Comment by Devik55** [comment]
new method for all lessons now

**Comment by Devik55** [comment]
no more reloading

**Comment by MichaelLookinForSumHcks** [comment]
w

**Comment by MichaelLookinForSumHcks** [comment]
can i try it rn?

**Comment by MichaelLookinForSumHcks** [comment]
rlly?

**Comment by Devik55** [comment]
yes its such an easy fix

**Comment by Devik55** [comment]
1 line of code

**Comment by MichaelLookinForSumHcks** [comment]
can i try it rn?

**Comment by Devik55** [comment]
yes

**Comment by MichaelLookinForSumHcks** [comment]
k

**Comment by Devik55** [comment]
update isnt pushe dyet

**Comment by Devik55** [comment]
pushed yet**

**Comment by MichaelLookinForSumHcks** [comment]
alr

**Comment by MichaelLookinForSumHcks** [comment]
leme know when its ready

**Comment by Devik55** [comment]
it should be now when you run the bookmark if the version text at the bottom is 2.2.1 your good

**Comment by MichaelLookinForSumHcks** [comment]
k

**Comment by MichaelLookinForSumHcks** [comment]
its loading...

**Comment by Devik55** [comment]
damn

**Comment by Devik55** [comment]
it worked when i ran it seperate from the script

**Comment by MichaelLookinForSumHcks** [comment]
> it should be now when you run the bookmark if the version text at the bottom is 2.2.1 your good

i cant find it?

**Comment by MichaelLookinForSumHcks** [comment]
> it worked when i ran it seperate from the script

oof

**Comment by Devik55** [comment]
?

**Comment by MichaelLookinForSumHcks** [comment]
uhhm did u ask chat gpt?

**Comment by Devik55** [comment]
bru i cant

**Comment by MichaelLookinForSumHcks** [comment]
> it should be now when you run the bookmark if the version text at the bottom is 2.2.1 your good

yea it says v2.2.1

**Comment by Devik55** [comment]
wait wtf it does work

**Comment by Devik55** [comment]
kinda of

**Comment by Devik55** [comment]
asssignment_id is 0 for some reason

**Comment by Devik55** [comment]
activity end is there

**Comment by MichaelLookinForSumHcks** [comment]
wt?

**Comment by MichaelLookinForSumHcks** [comment]
<img width="956" alt="image" src="https://github.com/user-attachments/assets/cde9b318-f4f0-4518-9876-51a9d3c51fdb">

**Comment by MichaelLookinForSumHcks** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/bb529998-5a4d-450e-b9d2-8fdc6200f5c7">

**Comment by MichaelLookinForSumHcks** [comment]
> asssignment_id is 0 for some reason

maybe cuz its not an assignment?

**Comment by MichaelLookinForSumHcks** [comment]
cuz when i clcik change data it says 
Unsupported lesson type. Only works on assignments.

**Comment by Devik55** [comment]
not change data use finishj lesson

**Comment by MichaelLookinForSumHcks** [comment]
honestly idk

**Comment by Devik55** [comment]
i know it cant work on those lessons because they dont have a saving system

**Comment by MichaelLookinForSumHcks** [comment]
it does

**Comment by Devik55** [comment]
the change data doesnt work

**Comment by MichaelLookinForSumHcks** [comment]
it goes to  practice grades

**Comment by MichaelLookinForSumHcks** [comment]
> the change data doesnt work

yea

**Comment by Devik55** [comment]
i found the actual error

**Comment by Devik55** [comment]
this time

**Comment by MichaelLookinForSumHcks** [comment]
pls tell me it works

**Comment by MichaelLookinForSumHcks** [comment]
<img width="955" alt="image" src="https://github.com/user-attachments/assets/b2ead53a-5ce1-47a1-b879-3bcabe673796">

**Comment by MichaelLookinForSumHcks** [comment]
> this time

tell me when the upd finishes

**Comment by Devik55** [comment]
sorry for the troubles

**Comment by MichaelLookinForSumHcks** [comment]
nah ur good

**Comment by MichaelLookinForSumHcks** [comment]
is it out yet?

**Comment by Devik55** [comment]
no just finished working on it

**Comment by Devik55** [comment]
YES IT WORKS

**Comment by MichaelLookinForSumHcks** [comment]
W

**Comment by MichaelLookinForSumHcks** [comment]
LEME TRY

**Comment by MichaelLookinForSumHcks** [comment]
i mean wait for the upd to push

**Comment by MichaelLookinForSumHcks** [comment]
THAN TRY

**Comment by MichaelLookinForSumHcks** [comment]
KK

**Comment by MichaelLookinForSumHcks** [comment]
ITS OUT

**Comment by Devik55** [comment]
updated now, it was tested and works

**Comment by Devik55** [comment]
thanks for being so paitent

**Comment by Devik55** [comment]
i think i have support for all lesson types now

**Comment by MichaelLookinForSumHcks** [comment]
yw

**Comment by Devik55** [comment]
tell me when you try it and if it works or not

**Comment by MichaelLookinForSumHcks** [comment]
OMG

**Comment by MichaelLookinForSumHcks** [comment]
TYSM

**Comment by MichaelLookinForSumHcks** [comment]
aye

**Comment by MichaelLookinForSumHcks** [comment]
offcialy closed
